name: Build

on:
  workflow_call:
  push:
  pull_request:
    branches:
      - master

env:
  CONFIGURE_PRESET: ci-release

jobs:
  build:
    strategy:
      matrix:
        api-version:
          - ref: fc5b443d86d10c5ce308630f8b41c8f64f5f40f1
            abi: 65
            patch-file: 4.1_0001-Support-building-plugins-without-an-install.patch
        platform:
          - name: ubuntu
            binary: libbinja-msvc.so
          - name: windows
            binary: binja-msvc.dll
          - name: macos
            binary: libbinja-msvc.dylib
    runs-on: ${{matrix.platform.name}}-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # Make sure Ninja is installed & we can create the stubs for Windows.
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Fetch binaryninja-api
      uses: actions/checkout@v4
      with:
        repository: Vector35/binaryninja-api
        ref: ${{matrix.api-version.ref}}
        path: binaryninja-api
        submodules: recursive
        sparse-checkout: |
          .
          python
          rapidjson
          rust
          cmake
          json
          vendor
          examples

    - name: Apply binaryninja-api patch
      working-directory: binaryninja-api
      run: git apply --verbose ../.github/${{matrix.api-version.patch-file}}

    - name: Build
      run: |
        cmake --preset ${{env.CONFIGURE_PRESET}}
        cmake --build build
        mv build/${{matrix.platform.binary}} build/${{matrix.api-version.abi}}-${{matrix.platform.binary}}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: lib-${{matrix.platform.name}}-${{matrix.api-version.abi}}
        path: build/${{matrix.api-version.abi}}-${{matrix.platform.binary}}
        if-no-files-found: error
